spring:
  profiles:
    active: default
  main:
    show_banner: false
# Redis properties
  redis:
   port: 6379
   host: localhost
   pool:
     maxIdle: 8 # max idle connections in the pool
     minIdle: 0 # min idle connections in the pool
     maxActive: -1 # no limit to the number of active connections
     maxWait: 30000 # time limit to get a connection - only applies if maxActive is finite      
  datasource:
    platform: mariadb      
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/testDB
    username: toto
    password: test123
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

