---
apiVersion: autoscaling/v1beta1
kind: HorizontalPodAutoscaler
metadata:
  name: spring-boot-assignment
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metricName: messages
      targetAverageValue: 10
---
apiVersion: autoscaling/v1beta1
kind: HorizontalPodAutoscaler
metadata:
  name: mariadb
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metricName: messages
      targetAverageValue: 10

